services:
  - type: web
    name: hotel-email-api
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10